### ISSUE TITLE
All of 3.3.2 are run locally

### ISSUE THREAD

**Issue by naftis** [naftis/opencrvs-mexico#13]
> kinda related to my reading comprehension because it's said in the very first sentence of the doc, but could it be clarified here https://documentation.opencrvs.org/setup/3.-installation/3.3-set-up-a-server-hosted-environment/3.3.2-install-dependencies that all of the following commands are run locally? I just assumed I need to involve the server someway here but actually not

**Comment by euanmillar** [comment]
I have added a hint at the top of the page to try to make this clear.
