### ISSUE TITLE
I had special characters in my DockerHub password

### ISSUE THREAD

**Issue by naftis** [naftis/opencrvs-mexico#15]
I couldn't get the logging in to DockerHub working (I had $!@ in my password), I tried escaping them in different ways, escaping all of them, escaping only \\$, but always got 401 Unauthorized. Ended up changing my password

**Comment by euanmillar** [comment]
I might not bother mentioning this.  Its more of a Dockerhub issue

**Comment by euanmillar** [comment]
I mentioned it
