### ISSUE TITLE
What are KIBANA_PASSWORD & KIBANA_USERNAME

### ISSUE THREAD

**Issue by naftis** [naftis/opencrvs-mexico#16]
_(I think I can just set them to anything, as the later step regarding monitoring refers to these, but confused me a bit)_

https://documentation.opencrvs.org/setup/3.-installation/3.3-set-up-a-server-hosted-environment/3.3.6-deploy
What are kibana pass and kibana user? Should I have these by now?

**Comment by euanmillar** [comment]
Done
