### ISSUE TITLE
Are dashes special characters?

### ISSUE THREAD

**Issue by naftis** [naftis/opencrvs-mexico#3]
https://documentation.opencrvs.org/setup/3.-installation/3.2-set-up-your-own-country-configuration/3.2.2-set-up-administrative-address-divisions/3.2.2.1-prepare-source-files-for-state-and-district-levels

> It is important to note that the statisticalID must contain no spaces, special characters or commas

Is dash a special character? Because uuid contains it.

**Comment by euanmillar** [comment]
Done!
