### ISSUE TITLE
Health facilities missing physicalType

### ISSUE THREAD

**Issue by naftis** [naftis/opencrvs-mexico#5]
https://documentation.opencrvs.org/setup/3.-installation/3.2-set-up-your-own-country-configuration/3.2.3-set-up-cr-offices-and-health-facilities/3.2.3.2-prepare-source-file-for-health-facilities

example CSV-table is missing `physicalType: "Building"`

**Comment by euanmillar** [comment]
physicalType is removed in v1.2
