### ISSUE TITLE
Confusing "Id" or "ID" casing?

### ISSUE THREAD

**Issue by naftis** [naftis/opencrvs-mexico#6]
https://documentation.opencrvs.org/setup/3.-installation/3.2-set-up-your-own-country-configuration/3.2.4-set-up-employees-for-testing-or-production/3.2.3.1-prepare-source-file-for-test-employees

It can be confusing when `statisticalID`/`facilityId` casing is different

**Comment by euanmillar** [comment]
No longer relevant as replaced with "id" in Humdata format for v1.2
